'use client'

import React, { useRef, useCallback } from 'react';
import styled from 'styled-components';
import { FaDownload, FaShareAlt, FaFilePdf, FaImage, FaCopy, FaCheck, FaBriefcase } from 'react-icons/fa';
import { Theme } from '../../styles/Theme';
import ProReportForm from '../TestResultActions/ProReportForm';

const ExportContainer = styled.div`
  display: flex;
  flex-wrap: wrap;
  gap: 0.75rem;
`;

const ExportButton = styled.button`
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.6rem 1rem;
  border: 1px solid ${Theme.border};
  border-radius: 8px;
  background: ${Theme.backgroundLight};
  color: ${Theme.textPrimary};
  font-size: 0.85rem;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.2s ease;
  
  svg {
    color: ${Theme.primary};
  }
  
  &:hover {
    background: ${Theme.surface};
    border-color: ${Theme.primary};
    transform: translateY(-1px);
  }
  
  &:active {
    transform: translateY(0);
  }
  
  &:disabled {
    opacity: 0.5;
    cursor: not-allowed;
    transform: none;
  }
`;

/**
 * Normalize healthScore to an object structure
 */
const normalizeHealthScore = (score) => {
    if (typeof score === 'object' && score !== null && score.total !== undefined) {
        return score;
    }

    const total = typeof score === 'number' ? score : 0;
    let grade = 'F';
    let gradeLabel = 'Critical Issues';

    if (total >= 95) { grade = 'S'; gradeLabel = 'Perfect Condition'; }
    else if (total >= 85) { grade = 'A'; gradeLabel = 'Great Condition'; }
    else if (total >= 70) { grade = 'B'; gradeLabel = 'Good Condition'; }
    else if (total >= 50) { grade = 'C'; gradeLabel = 'Fair Condition'; }
    else if (total >= 30) { grade = 'D'; gradeLabel = 'Poor Condition'; }

    return { total, grade, gradeLabel };
};

/**
 * Generate shareable text summary
 */
const generateTextSummary = (testData, rawHealthScore) => {
    const healthScore = normalizeHealthScore(rawHealthScore);
    const {
        controllerName = 'Controller',
        driftLeft = 0,
        driftRight = 0,
        latency = 0,
        buttonsWorking = 0,
        buttonsTotal = 16
    } = testData;

    return `🎮 ${controllerName} Health Report

📊 Health Score: ${healthScore.total}/100 (Grade ${healthScore.grade})

📋 Results:
• Drift: L ${driftLeft.toFixed(1)}% | R ${driftRight.toFixed(1)}%
• Latency: ${latency.toFixed(0)}ms
• Buttons: ${buttonsWorking}/${buttonsTotal} working

${healthScore.total >= 80 ? '✅ Great condition!' : healthScore.total >= 60 ? '⚠️ Needs attention' : '❌ Issues detected'}

Tested on MyGamepadTester.com`;
};

/**
 * Copy to clipboard with fallback
 */
const copyToClipboard = async (text) => {
    if (navigator.clipboard && navigator.clipboard.writeText) {
        await navigator.clipboard.writeText(text);
        return true;
    }

    // Fallback for older browsers
    const textArea = document.createElement('textarea');
    textArea.value = text;
    textArea.style.position = 'fixed';
    textArea.style.left = '-9999px';
    document.body.appendChild(textArea);
    textArea.select();

    try {
        document.execCommand('copy');
        return true;
    } catch (err) {
        return false;
    } finally {
        document.body.removeChild(textArea);
    }
};

/**
 * Generate PDF report using jsPDF
 */
const generatePDF = async (testData, rawHealthScore, customerData = null) => {
    const healthScore = normalizeHealthScore(rawHealthScore);
    // Dynamic import of jsPDF to reduce bundle size
    const { jsPDF } = await import('jspdf');

    const pdf = new jsPDF();
    const {
        controllerName = 'Controller',
        driftLeft: rawDriftLeft = 0,
        driftRight: rawDriftRight = 0,
        latency: rawLatency = 0,
        buttonsWorking = 0,
        buttonsTotal = 16,
        triggersFullRange = true
    } = testData;

    // Ensure numeric types
    const driftLeft = Number(rawDriftLeft) || 0;
    const driftRight = Number(rawDriftRight) || 0;
    const latency = Number(rawLatency) || 0;

    // Header
    pdf.setFillColor(218, 119, 86); // Theme primary
    pdf.rect(0, 0, 210, 40, 'F');

    pdf.setFontSize(24);
    pdf.setTextColor(255, 255, 255);
    pdf.text('Controller Health Certificate', 20, 25);

    pdf.setFontSize(10);
    pdf.text('Generated by MyGamepadTester.com', 140, 25);

    // Business info if available
    if (customerData) {
        pdf.setFillColor(245, 245, 245);
        pdf.rect(0, 40, 210, 30, 'F');

        pdf.setTextColor(0, 0, 0);
        pdf.setFontSize(10);
        pdf.setFont(undefined, 'bold');
        pdf.text('REPAIR / SERVICE DETAILS', 20, 50);

        pdf.setFont(undefined, 'normal');
        pdf.text(`Customer: ${customerData.customerName || 'N/A'}`, 20, 58);
        pdf.text(`Order/Ticket: ${customerData.orderNumber || 'N/A'}`, 120, 58);
        pdf.text(`Technician: ${customerData.technicianName || 'N/A'}`, 20, 64);
        pdf.text(`Serial #: ${customerData.serialNumber || 'N/A'}`, 120, 64);
    }

    // Controller name
    pdf.setFontSize(16);
    pdf.setTextColor(0, 0, 0);
    pdf.setFont(undefined, 'bold');
    pdf.text(`Device: ${controllerName}`, 20, customerData ? 85 : 55);

    // Date
    pdf.setFontSize(9);
    pdf.setTextColor(100, 100, 100);
    pdf.setFont(undefined, 'normal');
    pdf.text(`Test Date: ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}`, 20, customerData ? 92 : 62);

    // Health Score Box
    const scoreY = customerData ? 100 : 70;
    pdf.setDrawColor(218, 119, 86);
    pdf.setLineWidth(0.5);
    pdf.roundedRect(20, scoreY, 170, 40, 3, 3);

    const scoreColor = healthScore.total >= 80 ? [16, 185, 129] : healthScore.total >= 60 ? [245, 158, 11] : [239, 68, 68];
    pdf.setTextColor(scoreColor[0], scoreColor[1], scoreColor[2]);
    pdf.setFontSize(42);
    pdf.setFont(undefined, 'bold');
    pdf.text(`${healthScore.total}`, 45, scoreY + 28);

    pdf.setFontSize(14);
    pdf.text('/100', 80, scoreY + 28);

    pdf.setFontSize(24);
    pdf.text(`Grade: ${healthScore.grade}`, 110, scoreY + 22);

    pdf.setFontSize(10);
    pdf.setTextColor(100, 100, 100);
    pdf.setFont(undefined, 'normal');
    pdf.text(healthScore.gradeLabel, 110, scoreY + 32);

    // Detailed Results
    const detailsY = scoreY + 55;
    pdf.setFontSize(14);
    pdf.setTextColor(0, 0, 0);
    pdf.setFont(undefined, 'bold');
    pdf.text('Diagnostic Results', 20, detailsY);

    pdf.setFontSize(11);
    pdf.setFont(undefined, 'normal');
    const results = [
        { label: 'Left Stick Drift', value: `${driftLeft.toFixed(2)}%`, score: `${healthScore.breakdown?.drift?.score || 'N/A'}/25 pts` },
        { label: 'Right Stick Drift', value: `${driftRight.toFixed(2)}%`, score: '' },
        { label: 'Latency', value: `${latency.toFixed(1)}ms`, score: `${healthScore.breakdown?.latency?.score || 'N/A'}/25 pts` },
        { label: 'Buttons Working', value: `${buttonsWorking}/${buttonsTotal}`, score: `${healthScore.breakdown?.buttons?.score || 'N/A'}/25 pts` },
        { label: 'Trigger Range', value: triggersFullRange ? 'Full' : 'Limited', score: `${healthScore.breakdown?.triggers?.score || 'N/A'}/25 pts` }
    ];

    let rowY = detailsY + 10;
    results.forEach(result => {
        pdf.setTextColor(0, 0, 0);
        pdf.text(result.label + ':', 25, rowY);
        pdf.text(result.value, 90, rowY);
        if (result.score) {
            pdf.setTextColor(100, 100, 100);
            pdf.text(result.score, 140, rowY);
        }
        rowY += 10;
    });

    // Custom Notes if available
    if (customerData && customerData.notes) {
        pdf.setFontSize(12);
        pdf.setTextColor(0, 0, 0);
        pdf.setFont(undefined, 'bold');
        pdf.text('Technician Notes:', 20, rowY + 15);

        pdf.setFontSize(10);
        pdf.setFont(undefined, 'normal');
        pdf.setTextColor(50, 50, 50);
        const splitNotes = pdf.splitTextToSize(customerData.notes, 170);
        pdf.text(splitNotes, 20, rowY + 25);
    }

    // Footer
    pdf.setFontSize(9);
    pdf.setTextColor(150, 150, 150);
    pdf.text('Certified by MyGamepadTester.com - Direct diagnostics for professional repairs.', 20, 280);
    pdf.text(`ID: GP-${Math.random().toString(36).substr(2, 9).toUpperCase()}`, 150, 280);

    return pdf.output('blob');
};

/**
 * ShareExport Component
 * Provides buttons to share and export test results
 */
const ShareExport = ({ testData, healthScore, shareCardRef = null }) => {
    const [copySuccess, setCopySuccess] = React.useState(false);
    const [pdfLoading, setPdfLoading] = React.useState(false);
    const [showProForm, setShowProForm] = React.useState(false);

    const handleCopyResults = useCallback(async () => {
        const text = generateTextSummary(testData, healthScore || testData.healthScore);
        const success = await copyToClipboard(text);
        if (success) {
            setCopySuccess(true);
            setTimeout(() => setCopySuccess(false), 2000);
        }
    }, [testData, healthScore]);

    const handleDownloadPDF = useCallback(async (customerData = null) => {
        setPdfLoading(true);
        try {
            console.log("Generating PDF with data:", { testData, healthScore, customerData });
            const pdfBlob = await generatePDF(testData, healthScore || testData.healthScore, customerData);
            if (!pdfBlob) throw new Error("Could not generate PDF blob");
            console.log("PDF Blob generated successfully");

            const url = URL.createObjectURL(pdfBlob);
            const link = document.createElement('a');
            link.href = url;
            const suffix = customerData ? `pro-report` : `health-report`;
            link.download = `controller-${suffix}-${new Date().toISOString().split('T')[0]}.pdf`;
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
            URL.revokeObjectURL(url);
            if (customerData) setShowProForm(false);
        } catch (error) {
            console.error('PDF generation detailed fail:', error.message, error.stack);
            alert('Failed to generate PDF. Error: ' + error.message + '\n\nPlease check console for details or use the Copy Results button.');
        } finally {
            setPdfLoading(false);
        }
    }, [testData, healthScore]);

    const handleShareTwitter = useCallback(() => {
        const hs = normalizeHealthScore(healthScore || testData.healthScore);
        const text = `My controller scored ${hs.total}/100 (Grade ${hs.grade}) on MyGamepadTester.com! #GamepadTest`;
        const url = `https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}`;
        window.open(url, '_blank', 'width=550,height=420');
    }, [healthScore, testData]);

    const handleShareReddit = useCallback(() => {
        const hs = normalizeHealthScore(healthScore || testData.healthScore);
        const title = `Controller Health Score: ${hs.total}/100 (Grade ${hs.grade})`;
        const url = `https://reddit.com/submit?title=${encodeURIComponent(title)}&url=${encodeURIComponent('https://mygamepadtester.com')}`;
        window.open(url, '_blank');
    }, [healthScore, testData]);

    return (
        <ExportContainer>
            <ExportButton onClick={handleCopyResults}>
                {copySuccess ? <FaCheck color="#10B981" /> : <FaCopy />}
                {copySuccess ? 'Copied!' : 'Copy Results'}
            </ExportButton>

            <ExportButton onClick={() => handleDownloadPDF()} disabled={pdfLoading}>
                <FaFilePdf />
                {pdfLoading && !showProForm ? 'Generating...' : 'Download PDF'}
            </ExportButton>

            <ExportButton
                onClick={() => setShowProForm(true)}
                style={{ background: Theme.background, borderColor: Theme.primary }}
            >
                <FaBriefcase />
                Pro Report
            </ExportButton>

            <ExportButton onClick={handleShareTwitter}>
                <FaShareAlt />
                Share on X
            </ExportButton>

            <ExportButton onClick={handleShareReddit}>
                <FaShareAlt />
                Share on Reddit
            </ExportButton>

            {showProForm && (
                <ProReportForm
                    onClose={() => setShowProForm(false)}
                    onSubmit={handleDownloadPDF}
                    defaultData={{ technicianName: 'Admin' }}
                />
            )}
        </ExportContainer>
    );
};

export default ShareExport;
export { generatePDF, generateTextSummary, copyToClipboard };
